-- Заполнение таблицы с жанрами
INSERT INTO genre (genre_ru, genre_en, content_type, [description])
VALUES
    ('Боевик', 'Action', 'Film', NULL),
    ('Комедия', 'Comedy', 'Film', NULL),
    ('Драма', 'Drama', 'Film', NULL),
    ('Ужасы', 'Horror', 'Film', NULL),
    ('Фантастика', 'Science Fiction', 'Film', NULL),
    ('Триллер', 'Thriller', 'Film', NULL),
    ('Приключения', 'Adventure', 'Film', NULL),
    ('Мультфильм', 'Animation', 'Film', NULL),
    ('Фэнтези', 'Fantasy', 'Film', NULL),
    ('Криминал', 'Crime', 'Film', NULL),
    ('Мистика', 'Mystery', 'Film', NULL),
    ('Биография', 'Biography', 'Film', NULL),
    ('Вестерн', 'Western', 'Film', NULL),
    ('Военный', 'War', 'Film', NULL),
    ('Исторический', 'Historical', 'Film', NULL),
    ('Документальный', 'Documentary', 'Film', NULL),
    ('Музыкальный', 'Musical', 'Film', NULL),
    ('Романтический', 'Romantic', 'Film', NULL),
    ('Спортивный', 'Sports', 'Film', NULL),
    ('Детектив', 'Detective', 'Film', NULL),
    ('Детский', 'Children', 'Film', NULL),
    ('Политический', 'Political', 'Film', NULL);
-- Вставка жанров для типа "Cartoon"
INSERT INTO genre (genre_ru, genre_en, content_type, [description])
VALUES
    ('Мультфильм', 'Animation', 'Cartoon', NULL),
    ('Приключения', 'Adventure', 'Cartoon', NULL),
    ('Комедия', 'Comedy', 'Cartoon', NULL),
    ('Фэнтези', 'Fantasy', 'Cartoon', NULL),
    ('Семейный', 'Family', 'Cartoon', NULL),
    ('Мюзикл', 'Musical', 'Cartoon', NULL),
    ('Фантастика', 'Science Fiction', 'Cartoon', NULL),
    ('Драма', 'Drama', 'Cartoon', NULL),
    ('Экшн', 'Action', 'Cartoon', NULL),
    ('Мистика', 'Mystery', 'Cartoon', NULL),
    ('Детский', 'Children', 'Cartoon', NULL),
    ('Школа', 'School', 'Cartoon', NULL),
    ('Спорт', 'Sports', 'Cartoon', NULL),
    ('История', 'History', 'Cartoon', NULL),
    ('Киберпанк', 'Cyberpunk', 'Cartoon', NULL),
    ('Детектив', 'Detective', 'Cartoon', NULL),
    ('Шоу', 'Show', 'Cartoon', NULL),
    ('Пародия', 'Parody', 'Cartoon', NULL),
    ('Романтика', 'Romance', 'Cartoon', NULL),
    ('Демоны', 'Demons', 'Cartoon', NULL),
    ('Полиция', 'Police', 'Cartoon', NULL),
    ('Кошмары', 'Nightmares', 'Cartoon', NULL),
    ('Магия', 'Magic', 'Cartoon', NULL),
    ('Космос', 'Space', 'Cartoon', NULL);

-- Вставка жанров для типа "Series"
INSERT INTO genre (genre_ru, genre_en, content_type, [description])
VALUES
    ('Драма', 'Drama', 'Series', NULL),
    ('Комедия', 'Comedy', 'Series', NULL),
    ('Фантастика', 'Science Fiction', 'Series', NULL),
    ('Криминал', 'Crime', 'Series', NULL),
    ('Ужасы', 'Horror', 'Series', NULL),
    ('Триллер', 'Thriller', 'Series', NULL),
    ('Мелодрама', 'Melodrama', 'Series', NULL),
    ('Детектив', 'Detective', 'Series', NULL),
    ('Боевик', 'Action', 'Series', NULL),
    ('Мистика', 'Mystery', 'Series', NULL),
    ('Приключения', 'Adventure', 'Series', NULL),
    ('Семейный', 'Family', 'Series', NULL),
    ('Исторический', 'Historical', 'Series', NULL),
    ('Фэнтези', 'Fantasy', 'Series', NULL),
    ('Документальный', 'Documentary', 'Series', NULL),
    ('Музыкальный', 'Musical', 'Series', NULL),
    ('Романтический', 'Romantic', 'Series', NULL),
    ('Политический', 'Political', 'Series', NULL),
    ('Аниме', 'Anime', 'Series', NULL),
    ('Шоу', 'Show', 'Series', NULL),
    ('Спортивный', 'Sports', 'Series', NULL),
    ('Космос', 'Space', 'Series', NULL),
    ('Юмор', 'Humor', 'Series', NULL),
    ('Ток-шоу', 'Talk Show', 'Series', NULL);

-- Вставка жанров для типа "Anime"
INSERT INTO genre (genre_ru, genre_en, content_type, [description])
VALUES
    ('Аниме', 'Anime', 'Anime', NULL),
    ('Фантастика', 'Science Fiction', 'Anime', NULL),
    ('Приключения', 'Adventure', 'Anime', NULL),
    ('Экшн', 'Action', 'Anime', NULL),
    ('Фэнтези', 'Fantasy', 'Anime', NULL),
    ('Драма', 'Drama', 'Anime', NULL),
    ('Романтика', 'Romance', 'Anime', NULL),
    ('Школа', 'School', 'Anime', NULL),
    ('Мистика', 'Mystery', 'Anime', NULL),
    ('Магия', 'Magic', 'Anime', NULL),
    ('Меха', 'Mecha', 'Anime', NULL),
    ('Хентай', 'Hentai', 'Anime', NULL),
    ('Исторический', 'Historical', 'Anime', NULL),
    ('Триллер', 'Thriller', 'Anime', NULL),
    ('Ужасы', 'Horror', 'Anime', NULL),
    ('Сёдзё', 'Shoujo', 'Anime', NULL),
    ('Сёнэн', 'Shounen', 'Anime', NULL),
    ('Сейнэн', 'Seinen', 'Anime', NULL),
    ('Детский', 'Children', 'Anime', NULL),
    ('Спорт', 'Sports', 'Anime', NULL),
    ('Пародия', 'Parody', 'Anime', NULL),
    ('Боевые искусства', 'Martial Arts', 'Anime', NULL),
    ('Суперсила', 'Super Power', 'Anime', NULL),
    ('Музыка', 'Music', 'Anime', NULL);