INSERT INTO country (country_ru, country_en)
VALUES
    ('Россия', 'Russia'),
    ('США', 'United States'),
    ('Китай', 'China'),
    ('Индия', 'India'),
    ('Канада', 'Canada'),
    ('Бразилия', 'Brazil'),
    ('Австралия', 'Australia'),
    ('Япония', 'Japan'),
    ('Германия', 'Germany'),
    ('Франция', 'France'),
    ('Италия', 'Italy'),
    ('Великобритания', 'United Kingdom'),
    ('Испания', 'Spain'),
    ('Мексика', 'Mexico'),
    ('Южная Корея', 'South Korea'),
    ('Турция', 'Turkey'),
    ('Индонезия', 'Indonesia'),
    ('Нидерланды', 'Netherlands'),
    ('Швейцария', 'Switzerland'),
    ('Польша', 'Poland'),
    ('Швеция', 'Sweden'),
    ('Бельгия', 'Belgium'),
    ('Австрия', 'Austria'),
    ('Норвегия', 'Norway'),
    ('Дания', 'Denmark'),
    ('Финляндия', 'Finland'),
    ('ЮАР', 'South Africa'),
    ('Аргентина', 'Argentina'),
    ('Саудовская Аравия', 'Saudi Arabia'),
    ('Египет', 'Egypt'),
    ('Украина', 'Ukraine'),
    ('Чехия', 'Czech Republic'),
    ('Ирландия', 'Ireland'),
    ('Греция', 'Greece'),
    ('Португалия', 'Portugal'),
    ('Венгрия', 'Hungary'),
    ('Сингапур', 'Singapore'),
    ('Иран', 'Iran'),
    ('Израиль', 'Israel'),
    ('Малайзия', 'Malaysia'),
    ('Колумбия', 'Colombia'),
    ('Хорватия', 'Croatia'),
    ('Румыния', 'Romania'),
    ('Чили', 'Chile'),
    ('Таиланд', 'Thailand'),
    ('Болгария', 'Bulgaria'),
    ('Филиппины', 'Philippines'),
    ('Пакистан', 'Pakistan');